server:
  port: 8080

spring:
  application:
    name: tetrail-ticketing-system

  # 1. Cấu hình kết nối PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/tetrail
    username: hoang
    password: abcde
    driver-class-name: org.postgresql.Driver

  # 2. Cấu hình JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 3. Cấu hình thông số JWT (Bảo mật HMAC-SHA256 với Secret Key 256-bit)
jwt:
  # Chuỗi Hex 64 ký tự = 256 bits (đáp ứng tiêu chuẩn JJWT 0.12.6)
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  # Thời hạn Access Token: 86400000 ms = 24 giờ
  expiration: 86400000

# 4. Resilience4j cấu hình sẵn có của bạn
resilience4j:
  circuitbreaker:
    config:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  ratelimiter:
    instances:
      backendA:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
      backendB:
        limitForPeriod: 6
        limitRefreshPeriod: 500ms
        timeoutDuration: 3s

# 5. Spring Boot Actuator
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
